services:
  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hackernewsdb
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - hackernews-network
    ports:
      - "5432:5432"

networks:
  hackernews-network:
    driver: bridge

volumes:
  postgres-data:
